In [1]:
import numpy as np
from numpy import genfromtxt

In [2]:
data = genfromtxt('bank_note_data.txt',delimiter=',')
data

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699,   0.     ],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ,   0.     ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645,   0.     ],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ,   1.     ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ,   1.     ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ,   1.     ]])

In [3]:
labels = data[:,4]

In [4]:
labels

array([0., 0., 0., ..., 1., 1., 1.])

In [7]:
features = data[:,:-1]
features

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ]])

In [8]:
X = features
y = labels

In [9]:
from sklearn.model_selection import train_test_split

In [10]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [16]:
len(X_train)

1097

In [20]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

#Fitting only train coz we dont want the scaler to peek into the test data and cheat 
scaler.fit(X_train)

MinMaxScaler(copy=True, feature_range=(0, 1))

In [21]:
scaled_X_train = scaler.transform(X_train)
scaled_X_test = scaler.transform(X_test)

In [22]:
scaled_X_train.max()

1.0000000000000002

#### Building the network with keras. 

In [24]:
from keras.models import Sequential
from keras.layers import Dense


In [26]:
model = Sequential()

model.add(Dense(4, input_dim = 4, activation='relu'))

model.add(Dense(8, activation='relu'))
#Final layer
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

model.fit(scaled_X_train,y_train,epochs=100,verbose=2)


Epoch 1/100
 - 0s - loss: 0.7410 - acc: 0.4403
Epoch 2/100
 - 0s - loss: 0.7015 - acc: 0.4503
Epoch 3/100
 - 0s - loss: 0.6762 - acc: 0.5415
Epoch 4/100
 - 0s - loss: 0.6615 - acc: 0.5889
Epoch 5/100
 - 0s - loss: 0.6511 - acc: 0.6472
Epoch 6/100
 - 0s - loss: 0.6425 - acc: 0.6518
Epoch 7/100
 - 0s - loss: 0.6347 - acc: 0.6518
Epoch 8/100
 - 0s - loss: 0.6271 - acc: 0.6554
Epoch 9/100
 - 0s - loss: 0.6197 - acc: 0.6600
Epoch 10/100
 - 0s - loss: 0.6123 - acc: 0.6618
Epoch 11/100
 - 0s - loss: 0.6050 - acc: 0.6773
Epoch 12/100
 - 0s - loss: 0.5965 - acc: 0.6892
Epoch 13/100
 - 0s - loss: 0.5883 - acc: 0.6846
Epoch 14/100
 - 0s - loss: 0.5766 - acc: 0.6901
Epoch 15/100
 - 0s - loss: 0.5629 - acc: 0.6937
Epoch 16/100
 - 0s - loss: 0.5477 - acc: 0.7056
Epoch 17/100
 - 0s - loss: 0.5326 - acc: 0.7165
Epoch 18/100
 - 0s - loss: 0.5179 - acc: 0.7274
Epoch 19/100
 - 0s - loss: 0.5021 - acc: 0.7539
Epoch 20/100
 - 0s - loss: 0.4850 - acc: 0.7612
Epoch 21/100
 - 0s - loss: 0.4684 - acc: 0.7785
E

In [28]:
model.metrics_names

['loss', 'acc']

In [29]:
from sklearn.metrics import confusion_matrix, classification_report

In [30]:
predictions = model.predict_classes(scaled_X_test)

In [31]:
confusion_matrix(y_test, predictions)

array([[145,   3],
       [  3, 124]], dtype=int64)

In [32]:
print(classification_report(y_test,predictions))

             precision    recall  f1-score   support

        0.0       0.98      0.98      0.98       148
        1.0       0.98      0.98      0.98       127

avg / total       0.98      0.98      0.98       275



In [33]:
model.save('newModel.h5')

In [34]:
from keras.models import load_model

In [35]:
newmodel2 = load_model('newModel.h5')

In [36]:
newmodel2.predict_classes(scaled_X_test)

array([[0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
    